-- 4일차 집합연산자
-- 1.1 합집합
-- 1.1.1 UNION, UNION ALL(중복 허용)
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;    -- 19개 : 중복허용하지않아서

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION
SELECT EMP_NAME, EMP_ID FROM EMPLOYEE
WHERE SALARY >= 2400000; 
-- ORA-01790: expression must have same datatype as corresponding expression
-- UNION 사용 조건 1. 컬럼의 갯수가 같아야 함 2. 컬럼의 데이터타입이 각각 같아야 함.

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL
SELECT EMP_NAME, TO_NUMBER(EMP_ID) FROM EMPLOYEE    -- NUMBER로 형변환 해줌
WHERE SALARY >= 2400000; -- 다른 칼럼이어도 데이터 타입 맞췄으므로 값이 나온다!

-- 1.2 교집합 
-- 1.2.1 INTERSECT
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
INTERSECT
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;

-- 1.3 차집합
-- 1.3.1 MINUS
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
MINUS
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;
-- 첫번째 RESULT 에서 교집합이 된 것을 빼는 것.
-- 순서 중요하게 .. 